# Generated by Django 6.0.5 on 2026-05-20 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('dataset_upload', 'Dataset Upload'), ('dataset_activate', 'Dataset Activate'), ('dataset_delete', 'Dataset Delete'), ('export_report', 'Export Report'), ('role_change', 'Role Change'), ('user_status', 'User Status Change'), ('user_delete', 'User Delete')], max_length=40)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
